### ISSUE TITLE
클래스 명명 규칙

### ISSUE THREAD

**Issue by minikuma** [jasonchoi11/java-basic-study#1]
정답은 아니지만 **"Clean Code"** 라는 책에 보면, 
클래스 명은 명사 혹은 명사구로 사용하고 **Camel Case** 로 보통 표기합니다.
참고로 Manager, Processor, Data, Info 와 같은 너무 광범위한 단어도 피하는 게 좋아요.

클래스 명명 규칙에 따라 변경하는 것도 고려 해 보시면 좋을 거 같아요.

**Comment by jasonchoi11** [comment]
클래스 명을 명사로 바꾸고 파스칼 표기법으로 변경 했습니다. 
toLowCase -> LowercaseConverter
